[Pyxis]
refresh_time = 0.5 #In seconds

	[Pyxis.IP]
    FSM = "192.168.1.2"
    FSM_port = "4000"
		Navis = "192.168.1.3"
		Dextra = "192.168.1.4"#"192.168.1.4"
		Sinistra = "192.168.1.5"
		External = "150.203.91.206"

[Navis]


[Dextra]
   [Dextra.RobotControl]
    tab_name = "Robot Control"
    name = "DextraRobotControl"
    port = "4200"
    description = "Motor/Actuator control for the deputy Dextra"
    module_type = "RobotControlWidget"

    [Dextra.DeputyAux]
    tab_name = "Deputy Auxilliary"
    name = "DextraDeputyAux"
    port = "4201"
    description = "Dextra power system + LED controls"
    module_type = "DepAuxControlWidget"
    voltage_limit = 10
    
    [Dextra.StarTracker]
    tab_name = "Star Tracker Camera"
    name = "SinistraStarTracker"
    prefix = "CST"
    port = "4202"
    description = "Camera controls for the Dextra star tracker"
    module_type = "BaseFLIRCameraWidget"
    feed_refresh_time = 0.05
    compression_param = 2

    [Dextra.TargetControl]
    tab_name = "Target"
    name = "TargetControl"
    prefix = "TS"
    port = "4203"
    description = "Dextra Target selector (move to FSM?)"
    module_type = "TargetWidget"

[Sinistra]
