[Pyxis]
refresh_time = 0.5 #In seconds

	[Pyxis.IP]
    FSM = "192.168.1.2"
    FSM_port = "42000"
		Navis = "192.168.1.3"
		Dextra = "127.0.0.1"#"192.168.1.4"
		Sinistra = "192.168.1.5"
		External = "150.203.91.206"

[Navis]

[Dextra]

    [Dextra.TargetControl]
    tab_name = "Target"
    name = "TargetControl"
    prefix = "TS"
    port = "4000"
    description = "Dextra Target selector (move to FSM?)"
    module_type = "TargetWidget"
    
    [Dextra.STargetControl]
    tab_name = "STarget"
    name = "STargetControl"
    prefix = ""
    port = "4001"
    description = "Dextra Target selector (move to FSM?)"
    module_type = "ScienceCameraWidget"
    feed_refresh_time = 0.05
    compression_param = 1
    num_delays = 100
    GD_window_size = 50
    GD_scale = 0.5
    
    [Dextra.RobotControl]
    tab_name = "Robot Control"
    name = "DextraRobotControl"
    prefix = "RC"
    port = "4200"
    description = "Motor/Actuator control for the deputy Dextra"
    module_type = "RobotControlWidget"

    [Dextra.StarTracker]
    tab_name = "Star Tracker Camera"
    name = "DextraStarTracker"
    prefix = "CST"
    port = "4202"
    description = "Camera controls for the Dextra star tracker"
    module_type = "BaseFLIRCameraWidget"
    feed_refresh_time = 0.05
    compression_param = 1

    
    [Dextra.DeputyAux]
    tab_name = "Deputy Auxilliary"
    name = "DextraDeputyAux"
    port = "4201"
    description = "Dextra power system + LED controls"
    module_type = "DepAuxControlWidget"
    voltage_limit = 10
    power_refresh_time = 1

    [Dextra.ChiefAux]
    tab_name = "Chief Auxilliary"
    name = "DextraChiefAux"
    port = "4101"
    description = "Chief Aux"
    module_type = "ChiefAuxControlWidget"
    voltage_limit = 10
    status_refresh_time = 2
    
        [Dextra.ChiefAux.PiezoSteps]
        dextra_X = 0.1
        dextra_Y = 0.1
        sinistra_X = 1
        sinistra_Y = 1
        science = 2
                       
        [Dextra.ChiefAux.PiezoStart]
        dextra_X = 0.0
        dextra_Y = 0.0
        sinistra_X = 0.0
        sinistra_Y = 0.0
        science = 50

[Sinistra]
