port = "4106"
IP = "127.0.0.1"#"192.168.1.4"

[QHYCamera]
    [QHYcamera.camera]
    readout_mode = 2 #0 is HDR mode, 1 is STD LGC mode, 2 is STD HGC mode. Use 2!
    width = 100
    height = 120
    offset_x = 920
    offset_y = 940
    gain = 5
    gamma = 1.0
    black_level = 5 # Black level offset in ADU
    exposure_time = 3000 # in microseconds
    num_frames = 500 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 50000 #Size of circular buffer

    [QHYcamera.bounds]
    width = [32,2048]
    height = [32,2048]
    gain = [0,200]
    black_level = [0,20]
    exposure_time = [30,299000000]

    [QHYcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "data/test" #Default "where to save" file prefix
	
[ScienceCamera]
IP = "127.0.0.1"
CA_port = "4101"
TS_port = "4203"
tracking_period = 100
scanning_period = 500
xref = 71
yref = 45
numDelays = 3000
delaySize = 0.01
window_alpha = 0.95
gain = 0.4
SNRThreshold = 20.0
SNRReacqThreshold = 10.0
reacq_stepsize= 250
wave_offsets = [0,0,0,0,0,0]
    
    [ScienceCamera.FringeScanning]
    window_size = 20 #Number of frames to FFT over
    signal_width = 2 #How wide should the "signal" be in wavenumber steps
