port = "4106"
IP = "192.168.1.3"

[QHYCamera]
    [QHYcamera.camera]
    readout_mode = 2 #0 is HDR mode, 1 is STD LGC mode, 2 is STD HGC mode. Use 2!
    width = 100
    height = 120
    offset_x = 920
    offset_y = 940
    gain = 5 #Camera gain
    gamma = 1.0 #Camera gamma (should be 1!)
    black_level = 5 # Black level offset in ADU
    exposure_time = 3000 # in microseconds
    num_frames = 500 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 50000 #Size of circular buffer

    [QHYcamera.bounds]
    width = [32,2048]
    height = [32,2048]
    gain = [0,200]
    black_level = [0,20]
    exposure_time = [30,299000000]

    [QHYcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "data/test" #Default "where to save" file prefix
	
[ScienceCamera]
CA_port = "4101" #Chief aux port
TS_IP = "192.168.1.4" #Target server IP
TS_port = "4203" #Target server port
tracking_period = 100 #ms per step
scanning_period = 200 #ms per step
xref = 71 # X pixel position of the top most output row, reference wavelength (ref wavelength is defined in setup.cpp)
yref = 45 # Y pixel position of the top most output row, reference wavelength (ref wavelength is defined in setup.cpp)
wave_offsets = [0,0,0,0,0,0] # Relative X offsets between the wavelength reference pixels of the other rows (default all 0 if straight!)
numDelays = 3000 # How many delays?
delaySize = 0.01 # Spacing between delays (microns)
window_alpha = 0.95 #Fading memory parameter (0.95) 
gain = 0.2 #Gain for proportional controller (0.2)
SNRThreshold = 200.0 # SNR to achieve for fringe scan (200)
SNRReacqThreshold = 30.0 # SNR that when dropped below, will try to reacquire fringes (30)
reacq_stepsize= 250 # Number of steps to take in reacquisition sequence (multiply by 20nm for physical units)

