port = "4105"
IP = "127.0.0.1"


[FLIRcamera]
#cam_ID = "20031596"
cam_ID = "20031616"

    [FLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    width = 300
    height = 300
    offset_x = 0
    offset_y = 0
    gain = 1 #in dB
    black_level = 2 #in percent? ADU?
    exposure_time = 5000 # in microseconds
    num_frames = 0 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 200 #Size of circular buffer

    [FLIRcamera.bounds]
    width = [32,1440]
    height = [32,1080]
    gain = [0,48]
    black_level = [0.0,9.9]
    exposure_time = [30,29000000]

    [FLIRcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "data/test" #Default "where to save" file prefix

[FibreInjection]
FI_port = "4100"
IP = "192.168.1.3"

    [FibreInjection.Dextra]
    target_x = 593
    target_y = 431
    centre_x = 615
    centre_y = 450

    [FibreInjection.Sinistra]
    target_x = 619
    target_y = 629
    centre_x = 725
    centre_y = 695

    [FibreInjection.CoarseCentroid]
    interp_size = 9
    gaussian_radius = 9
    gaussian_window_size = 240
    WCOG_gain = 1.0
    WCOG_sigma = 4.0

    [FibreInjection.FineCentroid]
    interp_size = 9
    gaussian_radius = 9
    gaussian_window_size = 100
    WCOG_gain = 1.0
    WCOG_sigma = 4.0

