port = "4105"
IP = "192.168.1.3"



[FLIRcamera]
#cam_ID = "20031596"
cam_ID = "20031616"

    [FLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    width = 500
    height = 600
    offset_x = 420
    offset_y = 252
    gain = 1 #in dB
    black_level = 2 #in percent? ADU?
    exposure_time = 5000 # in microseconds
    num_frames = 0 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 200 #Size of circular buffer

    [FLIRcamera.bounds]
    width = [32,1440]
    height = [32,1080]
    gain = [0,48]
    black_level = [0.0,9.9]
    exposure_time = [30,29000000]

    [FLIRcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "data/test" #Default "where to save" file prefix

[FibreInjection]
CA_port = "4101"
IP = "127.0.0.1"
servo_gain = 0.5 #0.5

    [FibreInjection.Dextra]
    target_x = 594
    target_y = 430
    centre_x = 615
    centre_y = 450

    [FibreInjection.Sinistra]
    target_x = 632
    target_y = 628
    centre_x = 725
    centre_y = 695

    [FibreInjection.CoarseCentroid]
    interp_size = 5 #must be odd
    gaussian_radius = 15 #must be odd
    gaussian_window_size = 300 #must be even
    WCOG_gain = 1.0
    WCOG_sigma = 4.0

    [FibreInjection.FineCentroid]
    interp_size = 5 #must be odd
    gaussian_radius = 7 #must be odd
    gaussian_window_size = 100 #must be even
    WCOG_gain = 1.0
    WCOG_sigma = 4.0
