port = "4105"
IP = "192.168.1.3"

[FLIRcamera]
cam_ID = "USB\\VID_1E10&SRL_20031616"

    [FLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    width = 500
    height = 600
    offset_x = 420
    offset_y = 252
    gain = 1 #in dB
    black_level = 2 #in percent? ADU?
    exposure_time = 5000 # in microseconds
    num_frames = 0 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 200 #Size of circular buffer

    [FLIRcamera.bounds]
    width = [32,1440]
    height = [32,1080]
    gain = [0,48]
    black_level = [0.0,9.9]
    exposure_time = [30,29000000]

    [FLIRcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "data/test" #Default "where to save" file prefix

[FibreInjection]
CA_port = "4101" #Port for the chief auxillary board
servo_gain = 0.5 #0.5 seems ok?

    [FibreInjection.Dextra]
    target_x = 594 #Target x position for Dextra injection
    target_y = 430 #Target y position for Dextra injection
    centre_x = 615 #X position of the centre of Dextra injection FOV
    centre_y = 450 #Y position of the centre of Dextra injection FOV

    [FibreInjection.Sinistra]
    target_x = 632 #Target x position for Sinistra injection
    target_y = 628 #Target y position for Sinistra injection
    centre_x = 725 #X position of the centre of Sinistra injection FOV
    centre_y = 695 #Y position of the centre of Sinistra injection FOV

    # Parameters for the coarse centroiding (sending centroid position to deputy plate solver)
    [FibreInjection.CoarseCentroid]
    interp_size = 5 #must be odd, size to interpolate centroid
    gaussian_radius = 15 #must be odd, gaussian blur radius
    window_size = 300 #must be even, size of window to consider the centroid in
    WCOG_gain = 1.0 #Gain of weighted COG
    WCOG_sigma = 4.0 #Sigma of weighted COG

    # Parameters for the fine centroiding (sending centroid positions to t/t piezos)
    [FibreInjection.FineCentroid]
    interp_size = 5 #must be odd, size to interpolate centroid
    gaussian_radius = 7 #must be odd, gaussian blur radius
    window_size = 100 #must be even, size of window to consider the centroid in
    WCOG_gain = 1.0 #Gain of weighted COG
    WCOG_sigma = 4.0 #Sigma of weighted COG
