port = "4103"
IP = "127.0.0.1"

[FLIRcamera]
cam_ID = "20031594"
#cam_ID = "20031616"

    [FLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    width = 500
    height = 400
    offset_x = 100
    offset_y = 200
    gain = 1 #in dB
    black_level = 2 #in percent? ADU?
    exposure_time = 1000 # in microseconds
    num_frames = 0 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 200 #Size of circular buffer

    [FLIRcamera.bounds]
    width = [32,1440]
    height = [32,1080]
    gain = [0,48]
    black_level = [0.0,9.9]
    exposure_time = [30,29000000]

    [FLIRcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "toto" #Default "where to save" file prefix

[CoarseMet]
RB_port = "4200"
DA_port = "4201"
# IP = "192.168.1.4"
