port = "4001"
IP = "192.168.1.4"

[FLIRcamera]
cam_ID = "20031596"

    [FLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    width = 68
    height = 68
    offset_x = 456
    offset_y = 468
    gain = 0
    black_level = 0 #in percent
    exposure_time = 50000 # in microseconds
    num_frames = 0 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 100 #Size of circular buffer

    [FLIRcamera.fits]
    bitpix = 32
	filename_prefix = "data/test" #Default "where to save" file prefix

