port = "4001"
IP = "192.168.1.4"

[QHYCamera]
    [QHYcamera.camera]
    readout_mode = 2 #0 is HDR mode, 1 is STD LGC mode, 2 is STD HGC mode. Use 2!
    width = 50
    height = 50
    offset_x = 50
    offset_y = 50
    gain = 5 
    gamma = 1.0
    black_level = 5 # Black level offset in ADU
    exposure_time = 200000 # in microseconds
    num_frames = 500 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 200 #Size of circular buffer

    [QHYcamera.bounds]
    width = [32,2048]
    height = [32,2048]
    gain = [0,200]
    black_level = [0,20]
    exposure_time = [30,299000000]

    [QHYcamera.fits]
    bitpix = 32
	filename_prefix = "data/test" #Default "where to save" file prefix
