port = "4001"
IP = "192.168.1.4"

[QHYCamera]
    [QHYcamera.camera]
    readout_mode = 2 #0 is HDR mode, 1 is STD LGC mode, 2 is STD HGC mode. Use 2!
    width = 50
    height = 50
    offset_x = 50
    offset_y = 50
    gain = 20
    gamma = 1.0
    black_level = 10 # Black level offset in ADU
    exposure_time = 2000 # in microseconds
    num_frames = 500 #Number to take
    buffer_size = 10 #Set equal to numFrames unless concerned about memory. Will only save the last n images in the buffer. 

    [QHYcamera.fits]
    bitpix = 32
	filename_prefix = "data/test"
