[Pyxis]
refresh_time = 0.5 #In seconds

	[Pyxis.IP]
    FSM = "192.168.1.2"
    FSM_port = "42000"
		Navis = "192.168.1.3"
		Dextra = "127.0.0.1"#"192.168.1.4"
		Sinistra = "192.168.1.5"
		External = "150.203.91.206"

[Navis]

[Dextra]
    [Dextra.RobotControl]
    tab_name = "Robot Control"
    name = "DextraRobotControl"
    prefix = "RC"
    port = "4000"
    description = "Motor/Actuator control for the deputy Dextra"
    module_type = "RobotControlWidget"

    [Dextra.StarTracker]
    tab_name = "Star Tracker Camera"
    name = "DextraStarTracker"
    prefix = "ST"
    port = "4001"
    description = "Camera controls for the Dextra star tracker"
    module_type = "BaseFLIRCameraWidget"
    feed_refresh_time = 0.05
    compression_param = 1

		[Dextra.ScienceCamera]
    tab_name = "Science Camera"
    name = "DextraScienceCam"
    prefix = "SC"
    port = "4002"
    description = "Science Camera controls"
    module_type = "BaseQHYCameraWidget"
    feed_refresh_time = 0.05
    compression_param = 1

    [Dextra.DeputyAux]
    tab_name = "Deputy Auxilliary"
    name = "DextraDeputyAux"
    prefix = "DA"
    port = "4003"
    description = "Dextra power system + LED controls"
    module_type = "PowerControlWidget"


[Sinistra]
