[Pyxis]
refresh_time = 0.5 #In seconds

	[Pyxis.IP]
        FSM = "192.168.1.2"
        FSM_port = "42000"
		Navis = "192.168.1.3"
		Dextra = "192.168.1.4"
		Sinistra = "192.168.1.5"
		External = "150.203.91.206"

[Navis]

[Dextra]
    [Dextra.RobotControl]
    tab_name = "Robot Control"
    name = "DextraRobotControl"
    port = "4000"
    description = "Motor/Actuator control for the deputy Dextra"
    module_type = "RobotControlWidget"

    [Dextra.StarTracker]
    tab_name = "Star Tracker Camera"
    name = "DextraStarTracker"
    port = "4001"
    description = "Camera controls for the Dextra star tracker"
    module_type = "BaseCameraWidget"
    feed_refresh_time = 2

    [Dextra.PowerSystem]
    tab_name = "Power System"
    name = "DextraPowerSystem"
    port = "4002"
    description = "Dextra power system + LED controls"
    module_type = "PowerControlWidget"


[Sinistra]
