
[QHYCamera]
    [QHYcamera.camera]
    acquisition_mode = 1 #0 is single frame mode, 1 is video stream mode
    readout_mode = 0 #...
    pixel_format = 16 #16 or 8 bit image? 16 by default
    width = 68
    height = 68
    offset_x = 456
    offset_y = 468
    gain = 0
    black_level = 0 #
    exposure_time = 5000 # in microseconds
    num_frames = 10
    buffer_size = 10 #Set equal to numFrames unless concerned about memory


    [testFLIRcamera.fits]
    bitpix = 32
    file_dir = "../data/"
    filename = "myfits2.fits"
