output_folder = "output" #Folder for output
IP = "121.01.12.13"
camera_port = "5555"
robot_control_port = "5555"

[Tetra3]
bg_sub_mode = "local_mean" #"Continuous" is default
sigma_mode = "global_root_square" #"Mono16" is default
filt_size = 15 #Size of filter

[Astrometry]
depth = 10 #How many stars to match?
FOV_min = 0.5 #minimum estimate of FOV in degrees
FOV_max = 1 #maximum estimate of FOV in degrees

    [Astrometry.estimate_position]
    flag = 0
    ra = 0
    dec = 0
    rad = 900
