output_folder = "output" #Folder for output
IP = "192.168.1.3"
camera_port = "4102"
camera_port_name = "FST"
robot_control_port = "4100"
target_IP = "192.168.1.4"
target_port = "4203"

platesolver_index = 0

path_to_data = "/home/pyxisuser/pyxis/servers/fine_star_tracker"

[Tetra3]
bg_sub_mode = "local_mean" #"Continuous" is default
sigma_mode = "global_root_square" #"Mono16" is default
filt_size = 15 #Size of filter

[Astrometry]
depth = 10 #How many stars to match?
FOV_min = 0.7 #minimum estimate of FOV in degrees
FOV_max = 1.5 #maximum estimate of FOV in degrees
ref_pix_x = 1536 #x reference pixel for WCS solution
ref_pix_y = 1024 #y reference pixel for WCS solution

    [Astrometry.estimate_position]
    flag = 0
    ra = 0
    dec = 0
    rad = 5
