output_folder = "output" #Folder for output
IP = "192.168.1.5"
camera_port = "4302"
camera_port_name = "CST"
robot_control_port = "4300"
target_port = "4303"
path_to_data = "/home/pyxisuser/git/pyxis/servers/coarse_star_tracker"

[Tetra3]
bg_sub_mode = "local_mean" #"Continuous" is default
sigma_mode = "global_root_square" #"Mono16" is default
filt_size = 15 #Size of filter

[Astrometry]
depth = 10 #How many stars to match?
FOV_min = 5 #minimum estimate of FOV in degrees
FOV_max = 6 #maximum estimate of FOV in degrees
ref_pix_x = 700 #x reference pixel for WCS solution
ref_pix_y = 500 #y reference pixel for WCS solution

    [Astrometry.estimate_position]
    flag = 0
    ra = 0
    dec = 0
    rad = 5
