[camera]
adc_bit_depth = "Bit10"
acquisition_mode = "Continuous"
pixel_format = "Mono16"
width = 900
height = 900
offset_x = 240
offset_y = 48
gain = 25
exposure_time = 50 # in microseconds
num_frames = 25

[fits]
buffer_size = 25 #Set equal to numFrames unless concerned about memory
bitpix = 32
file_dir = "../data/"
filename = "biasFrames.fits"
