[camera]
auto_exposure = "Off"
auto_gain = "Off"
adc_bit_depth = "Bit10"
acquisition_mode = "Continuous"
pixel_format = "Mono16"
width = 1000
height = 1000
offset_x = 0
offset_y = 0
exposure_time = 30 # in microseconds
num_frames = 1000

[fits]
buffer_size = 1000 #Set equal to numFrames unless concerned about memory
bitpix = 16
file_dir = "../data/"
filename = "biasFrames.fits"
