[camera]
adc_bit_depth = "Bit10" #"Bit10" is a good default
acquisition_mode = "Continuous" #"Continuous" is default
pixel_format = "Mono16" #"Mono16" is default
width = 1000
height = 1000
offset_x = 0
offset_y = 0
gain = 0
black_level = 0 #in percent
exposure_time = 2000 # in microseconds
num_frames = 10
buffer_size = 2 #Set equal to numFrames unless concerned about memory

[camera.trigger]
trigger_mode = "Off" #Is trigger on or off?
trigger_selector = "FrameStart" #"FrameStart" is default
trigger_source = "Software" #"Software", or "Line0, Line1 or Line2"

[fits]
bitpix = 32
file_dir = "../data/"
filename = "myfits.fits"

[fringe.locking]
selections = [["A",1],["A",3],["B",2]]
exposure_time =
scan_rate =
scan_width = 2e-3
lock_SNR =
window_size = 1000
signal_size = 2

[fringe.positions]
A.frequencies = [600e-9,630e-9,660e-9,690e-9,720e-9]
A.indices = [183,184,185,186,187]
B.frequencies = [600e-9,630e-9,660e-9,690e-9,720e-9]
B.indices = [483,484,485,486,487]
C.frequencies = [600e-9,630e-9,660e-9,690e-9,720e-9]
C.indices = [783,784,785,786,787]
