[camera]
auto_exposure = "Off"
manual_fps = "ON"
auto_gain = "Off"
adc_bit_depth = "Bit10"
acquisition_mode = "Continuous"
pixel_format = "Mono16"
width = 32
height = 32
offset_x = 0
offset_y = 0
exposure_time = 20000 # in microseconds
num_frames = 200

[fits]
buffer_size = 200 #Set equal to numFrames unless concerned about memory
bitpix = 16 #Set the same as pixel_format, but as an int
file_dir = "../data/"
filename = "myfits.fits"
