[camera]
auto_exposure = "Off"
auto_gain = "Off"
adc_bit_depth = "Bit10"
acquisition_mode = "Continuous"
pixel_format = "Mono16"
width = 32
height = 32
offset_x = 0
offset_y = 0
gain = 1
exposure_time = 20000 # in microseconds
num_frames = 5

[fits]
buffer_size = 5 #Set equal to numFrames unless concerned about memory
bitpix = 32
file_dir = "../data/"
filename = "myfits.fits"
