
[testFLIRcamera]
    [testFLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    acquisition_mode = "Continuous" #"Continuous" is default
    pixel_format = "Mono16" #"Mono16" is default
    width = 1000
    height = 1000
    offset_x = 0
    offset_y = 0
    gain = 0
    black_level = 0 #in percent
    exposure_time = 2000 # in microseconds
    num_frames = 10
    buffer_size = 2 #Set equal to numFrames unless concerned about memory

        [testFLIRcamera.camera.trigger]
        trigger_mode = "Off" #Is trigger on or off?
        trigger_selector = "FrameStart" #"FrameStart" is default
        trigger_source = "Software" #"Software", or "Line0, Line1 or Line2"

    [testFLIRcamera.fits]
    bitpix = 32
    file_dir = "../data/"
    filename = "myfits.fits"


[fringe]
    [fringe.locking]
    exposure_time = 10000 #In microseconds
    scan_rate = 3e-4 #In m/s
    scan_width = 1e-3 #In m
    start_pos = 1.0 #Start actuator position of scan in mm

    #FFT version
    selections = [["A",1],["A",3],["B",2]] #What channels to look at?
    lock_SNR = 0.9 #SNR to achieve for fringe locking
    window_size = 10 #Number of frames to FFT over
    signal_size = 2 #How wide should the "signal" be in wavenumber steps

    #Visibility version
    lock_vis = 0.5 #What V^2 value should trigger fringes being found?

    [fringe.positions]
    num_channels = 5
    #Frequencies and indices for those frequencies for each interferometer
    #spectral channel
    A.frequencies = [600e-9,630e-9,660e-9,690e-9,720e-9]
    A.indices = [183,184,185,186,187]
    B.frequencies = [600e-9,630e-9,660e-9,690e-9,720e-9]
    B.indices = [483,484,485,486,487]
    C.frequencies = [600e-9,630e-9,660e-9,690e-9,720e-9]
    C.indices = [783,784,785,786,787]

[testZaberActuator]
    serial_port = "/dev/ttyS2"
    device_number = 1
    home_speed = 1000 #um/s
    target_speed = 1000 #um/s
    microstep_resolution = 128
    device_mode = [11]
    #Device Mode values (add value to table to set mode (https://www.zaber.com/w/Manuals/T-NA)):
    #Set mode before HOME
    #Defaults in brackets
    #0 = Disable Auto Reply (OFF)
    #1 = Enable Anti-backlash routine (OFF)
    #2 = Enable Anti-stiction routine (OFF)
    #3 = Disable Potentiometer (OFF)
    #4 = Enable Move Tracking (OFF)
    #5 = Disable Manual Move Tracking (OFF)
    #6 = Enable Message IDs (OFF)
    #7 = Home Status (OFF)
    #8 = Disable Auto-Home (OFF)
    #9 = Reverse Potentiometer (OFF)
    #11 = Microstepping Mode (ON)
