[camera]
auto_exposure = "Off"
auto_gain = "Off"
adc_bit_depth = "Bit10"
acquisition_mode = "Continuous"
pixel_format = "Mono16"
width = 32
height = 32
offset_x = 0
offset_y = 0
exposure_time = 200 # in microseconds
numFrames = 200

[fits]
bufferSize = 200
fileDir = "../data/"
filename = "myfits.fits"
