[testFLIRcamera]
    [testFLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    acquisition_mode = "Continuous" #"Continuous" is default
    pixel_format = "Mono16" #"Mono16" is default
    width = 900
    height = 900
    offset_x = 500
    offset_y = 100
    gain = 15
    black_level = 3 #in percent
    exposure_time = 50 # in microseconds
    num_frames = 25
    buffer_size = 25 #Set equal to numFrames unless concerned about memory

        [testFLIRcamera.camera.trigger]
        trigger_mode = "Off" #Is trigger on or off?
        trigger_selector = "FrameStart" #"FrameStart" is default
        trigger_source = "Software" #"Software", or "Line0, Line1 or Line2"

    [testFLIRcamera.fits]
    bitpix = 32
    file_dir = "../data/"
    filename = "biasFrames.fits"
