[Pyxis]
refresh_time = 2 #In seconds

	[Pyxis.IP]
		Navis = "192.168.1.3"
		Dextra = "192.168.1.4"
		Sinistra = "192.168.1.5"
		External = "150.203.91.206"

[Navis]
    [Navis.RobotControl]
    tab_name = "RobotControl"
    name = "NavisRobotControl"
    port = 43000
    description = "Motor/actuator control for the central robot Navis"
    module_type = "RobotControlWidget"

    [Navis.StarTracker]
    tab_name = "Star Tracker Camera"
    name = "NavisStarTracker"
    port = 43001
    description = "Navis star tracker camera control"
    module_type = "RawWidget"

    [Navis.CourseMetrology]
    tab_name = "Course Met Camera"
    name = "NavisCourseMetrology"
    port = 43002
    description = "Course metrology camera control"
    module_type = "CameraWidget"

    [Navis.FiberInjection]
    tab_name = "Fiber Injection Camera"
    name = "NavisFiberInjection"
    port = 43003
    description = "Fiber injection camera control"
    module_type = "CameraWidget"

    [Navis.FineMetrology]
    tab_name = "Fine Metrology"
    name = "NavisFineMetrology"
    port = 43004
    description = "Fine interferometric metrology controls"
    module_type = "RawWidget"

    [Navis.TOSMetrology]
    tab_name = "TOS Metrology"
    name = "NavisTOSMetrology"
    port = 43005
    description = "Time of flight metrology controls"
    module_type = "RawWidget"

    [Navis.Gyro]
    tab_name = "Gyro"
    name = "NavisGyro"
    port = 43006
    description = "Gyro controls"
    module_type = "RawWidget"

    [Navis.ScienceCamera]
    tab_name = "Science Camera"
    name = "NavisScienceCamera"
    port = 43007
    description = "Science camera controls"
    module_type = "CameraWidget"

    [Navis.PowerSystem]
    tab_name = "Power System"
    name = "NavisPowerSystem"
    port = 43008
    description = "Navis power system + LED controls"
    module_type = "PowerControlWidget"

[Dextra]
    [Dextra.RobotControl]
    tab_name = "Robot Control"
    name = "DextraRobotControl"
    port = 44000
    description = "Motor/Actuator control for the deputy Dextra"
    module_type = "RobotControlWidget"

    [Dextra.StarTracker]
    tab_name = "Star Tracker Camera"
    name = "DextraStarTracker"
    port = 44001
    description = "Camera controls for the Dextra star tracker"
    module_type = "CameraWidget"

    [Dextra.PowerSystem]
    tab_name = "Power System"
    name = "DextraPowerSystem"
    port = 44002
    description = "Dextra power system + LED controls"
    module_type = "PowerControlWidget"

[Sinistra]
    [Sinistra.RobotControl]
    tab_name = "Robot Control"
    name = "SinistraRobotControl"
    port = 45000
    description = "Motor/Actuator control for the deputy Sinistra"
    module_type = "RobotControlWidget"

    [Sinistra.StarTracker]
    tab_name = "Star Tracker Camera"
    name = "SinistraStarTracker"
    port = 45001
    description = "Camera controls for the Sinistra star tracker"
    module_type = "CameraWidget"

    [Sinistra.PowerSystem]
    tab_name = "Power System"
    name = "SinistraPowerSystem"
    port = 45002
    description = "Sinistra power system + LED controls"
    module_type = "PowerControlWidget"
