port = "4203"
IP = "127.0.0.1"


[testZaberActuator]
    serial_port = "/dev/ttyS2"
    device_number = 1
    home_speed = 1000 #um/s
    target_speed = 1000 #um/s
    microstep_resolution = 128
    device_mode = [11]
    #Device Mode values (add value to table to set mode (https://www.zaber.com/w/Manuals/T-NA)):
    #Set mode before HOME
    #Defaults in brackets
    #0 = Disable Auto Reply (OFF)
    #1 = Enable Anti-backlash routine (OFF)
    #2 = Enable Anti-stiction routine (OFF)
    #3 = Disable Potentiometer (OFF)
    #4 = Enable Move Tracking (OFF)
    #5 = Disable Manual Move Tracking (OFF)
    #6 = Enable Message IDs (OFF)
    #7 = Home Status (OFF)
    #8 = Disable Auto-Home (OFF)
    #9 = Reverse Potentiometer (OFF)
    #11 = Microstepping Mode (ON)
