port = "4102"
IP = "192.168.1.3"

[FLIRcamera]
cam_ID = "20186458"
sleep_time = 1000 #Time to sleep in waiting loop

    [FLIRcamera.camera]
    adc_bit_depth = "Bit14" #"Bit10" is a good default
    width = 3072
    height = 2048
    offset_x = 0
    offset_y = 0
    gain = 30 #in dB
    black_level = 2 #in percent? ADU?
    exposure_time = 400000 # in microseconds
    num_frames = 0 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 20 #Size of circular buffer

    [FLIRcamera.bounds]
    width = [32,3072]
    height = [32,2048]
    gain = [0,48]
    black_level = [0.0,9.9]
    exposure_time = [30,29000000]

    [FLIRcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "data/test" #Default "where to save" file prefix

[FineStarTracker]
RB_port = "4100" # Navis robot port
platescale = 7.5e-6 #Platescale of camera (radians per pixel)
Centroid_exptime = 10000 #Exposure time for centroid mode
PlateSolve_exptime = 250000 #Exposure time for plate solving mode
centroid_x_target = 720.0 #X target coordinate of centroid
centroid_y_target = 540.0 #Y target coordinate of centroid 

