port = "4302"
IP = "192.168.1.5"

[FLIRcamera]
#cam_ID = "20031596"
cam_ID = "20031594"

    [FLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    width = 1440
    height = 1080
    offset_x = 0
    offset_y = 0
    gain = 25 #in dB
    black_level = 2 #in percent? ADU?
    exposure_time = 250000 # in microseconds
    num_frames = 1 #Default number of frames to save per FITS file; 0 is continuous with no saving
    buffer_size = 20 #Size of circular buffer
    num_savefiles = 1000

    [FLIRcamera.bounds]
    width = [32,1440]
    height = [32,1080]
    gain = [0,48]
    black_level = [0.0,9.9]
    exposure_time = [30,29000000]

    [FLIRcamera.fits]
    bitpix = 20 #USHORT_IMG = 20, not 16!
	filename_prefix = "data/test" #Default "where to save" file prefix

