
output_folder = "Bit10" #Folder for output

[Tetra3]
bg_sub_mode = "Continuous" #"Continuous" is default
sigma_mode = "Mono16" #"Mono16" is default
filt_size = 15 #Size of filter

[Astrometry]
depth = 10 #How many stars to match?
FOV_min = 5 #minimum estimate of FOV in degrees
FOV_max = 6 #maximum estimate of FOV in degrees
