
[FLIRcamera]
    [FLIRcamera.camera]
    adc_bit_depth = "Bit10" #"Bit10" is a good default
    acquisition_mode = "Continuous" #"Continuous" is default
    pixel_format = "Mono16" #"Mono16" is default
    width = 68
    height = 68
    offset_x = 456
    offset_y = 468
    gain = 0
    black_level = 0 #in percent
    exposure_time = 50000 # in microseconds
    num_frames = 10
    buffer_size = 10 #Set equal to numFrames unless concerned about memory

    [FLIRcamera.fits]
    bitpix = 32
	filename_prefix = "data/test"

